const emailVerification = (userName: string) => {
  return `<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>2FA Enabled Notification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }

        .container {
            width: 100%;
            max-width: 600px;
            margin: auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #4CAF50;
        }

        p {
            line-height: 1.6;
        }

        .footer {
            margin-top: 20px;
            font-size: 0.9em;
            color: #777;
        }

        .button {
            display: inline-block;
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
        }

        .button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Two-Factor Authentication Enabled</h1>
        <p>Hi ${userName},</p>
        <p>We're excited to inform you that Two-Factor Authentication (2FA) has been successfully enabled for your account. This adds an extra layer of security to help protect your personal information and account access.</p>
        <p>Whenever you log in, you will now need to enter a verification code sent to your mobile device or generated by your authentication app.</p>
        <p>If you did not request this change or want to remove 2FA, you can do so by logging into your account. You will receive an email verification to confirm the removal of 2FA.</p>
        <p>If you have any questions or need assistance, feel free to <a href="[Your Support Link]">contact our support team</a>.</p>
        <p>Thank you for prioritizing your account security!</p>
    </div>
</body>

</html>
`;
};

export default emailVerification;
